[versions]
compose = "1.6.2"
compose-plugin = "1.5.12"
compose-compiler = "1.5.4"
agp = "8.2.2"
android-minSdk = "24"
android-compileSdk = "34"
android-targetSdk = "34"
androidx-activityCompose = "1.8.2"
kotlin = "1.9.20"
kotlinxCoroutinesCore = "1.7.3"
multiplatformSettings = "1.1.1"
realm = "1.13.0"
voyagerVersion = "1.0.0"
koin = "3.4.3"
koin-compose = "1.0.4"
ktor-version = "2.3.8"

[libraries]
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }

#Ktor
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor-version" }
ktor-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor-version" }
ktor-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor-version" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor-version" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor-version" }
ktor-ios = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor-version" }
ktor-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor-version" }

#Koin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }

#Voyager
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyagerVersion" }
voyager-tab-navigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyagerVersion" }
voyager-screenModel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyagerVersion" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyagerVersion" }

multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
realm = { module = "io.realm.kotlin:library-base", version.ref = "realm" }

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }